config/routes.rb
Chatter::Application.routes.draw do
  resources :relationships

  get 'buddies', to: 'users#buddies', as: 'buddies'
  
  resources :chats

  get "sessions/new"

  post "sessions/create"

  get "sessions/destroy"

  root to: 'users#new'
  resources :users

end

app/models/chat.rb
class Chat < ActiveRecord::Base
  default_scope order: 'created_at DESC'
  attr_accessible :content, :user_id
  belongs_to :user
  validates :content, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :followed_id, :follower_id
  belongs_to :follower , class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :avatar_url, :email, :name, :password, :password_confirmation, :username
  before_validation :prep_email
  before_save :create_avatar_url
  has_secure_password
  has_many :chats
  has_many :follower_relationships, class_name: "Relationship", foreign_key: "followed_id"
  has_many :followed_relationships, class_name: "Relationship", foreign_key: "follower_id"
  has_many :followers, through: :follower_relationships
  has_many :followeds, through: :followed_relationships

  validates :name, presence: true
  validates :username, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true, format: { with: /^[\w.+-]+@([\w]+.)+\w+$/ }
  
def following? user
  self.followeds.include? user
end

def follow user
  Relationship.create follower_id: self.id, followed_id: user.id
end

private
def prep_email
	self.email = self.email.strip.downcase if self.email	
end

def create_avatar_url
	self.url = "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(self.email)}?s=50"
end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
	def create
		@chat = Chat.new(params[:chat])
		@chat.user_id = current_user.id
		if @chat.save
			redirect_to current_user
		else
			flash[:error] = "Problem!"
			redirect_to current_user
		end
	end

	def index
		@chats = Chat.all include: :user
		@chat = Chat.new		
	end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

def create
    @relationship = Relationship.new
    @relationship.followed_id = params[:followed_id]
    @relationship.follower_id = current_user.id
	if @relationship.save
    	redirect_to User.find params[:followed_id]
	else
        flash[:error] = "Couldn't Follow"
        redirect_to user
	end
end

def destroy
    @relationship = Relationship.find(params[:id])
    @relationship.destroy
    redirect_to user_path params[:id]
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_username(params[:username])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to user, notice: "Logged in!"
  	else
  		flash[:error] = "Wrong Username or password."
  		redirect_to root_url
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url, notice: "Logged out!"
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
	if current_user
		redirect_to buddies_path
	else
		@user = User.new
	end
end

def index
	@users = User.all
end

def buddies
	if current_user
		@chat = Chat.new
		buddies_ids = current_user.followeds.map(&:id).push(current_user.id)
		@chats = Chat.find_all_by_user_id buddies_ids
	else
		redirect_to user
	end
end

def create
	@user =User.new(params[:user])
	if @user.save
		session[:user_id] = @user.id
		redirect_to @user, notice: "Thank you for signing up for Chatter"
	else
		render 'new'
	end
end

def show
	@user = User.find(params[:id])
	@chat = Chat.new
	@relationship = Relationship.where(
    follower_id: current_user.id,
    followed_id: @user.id
	).first_or_initialize if current_user
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/index.html.erb
<% if current_user %>
<div id="createRibbit" class="panel right">
    <h1>Create a Chat</h1>
    <p>
    <%= form_for @chat do |f| %>
        <%= f.text_area :content, class: 'ribbitText' %>
        <%= f.submit "Chat!" %>
    <% end %>
    </p>
</div>
<% end %>
<div class="panel left">
    <h1>Public Chats</h1>
    <% @chats.each do |chat| %>
        <div class="ribbitWrapper">
            <a href="<%= user_path chat.user %>">
            <img class="avatar" src="<%= chat.user.url %>">
            <span class="name"><%= chat.user.name %></span>
            </a>
            @<%= chat.user.username %>
            <span class="time"><%= time_ago_in_words(chat.created_at) %></span>
            <p> <%= chat.content %> </p>
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
</head>
<body>
    <header>
        <div class="wrapper">
            <%= image_tag("gfx/logo.png") %>
            <% if current_user %>
            <%= link_to "Public Chats", chats_path %> &nbsp
            <%= link_to "Public Profiles", users_path %> &nbsp
            <%= link_to "My Profile", current_user %> &nbsp
            
            <%= link_to "Buddies Chats", buddies_path %> &nbsp
                <%= link_to "Log Out", sessions_destroy_path %>
            <% else %>
            <%= form_tag sessions_create_path do %>
                <%= text_field_tag :username, nil, placeholder: "username" %>
                <%= password_field_tag :password, nil,  placeholder: "password" %>
                <%= submit_tag "Log In" %>
            <% end %>
    </div>
<% end %>
    </header>
    <div id="content">
        <div class="wrapper">
            <% flash.each do |name, msg| %>
                <%= content_tag :div, msg, class: "flash #{name}" %>
            <% end %>
            <%= yield %>
        </div>
    </div>
    <footer>
        <div class="wrapper">
            Chatter - A innovative way to chat.<%= image_tag("gfx/logo-goldie.png") %>
        </div>
    </footer>
</body>
</html>

app/views/users/buddies.html.erb
<% if current_user %>
<div id="createRibbit" class="panel right">
    <h1>Create a Chatter</h1>
    <p>
    <%= form_for @chat do |f| %>
        <%= f.text_area :content, class: 'ribbitText' %>
        <%= f.submit "Chat!" %>
    <% end %>
    </p>
</div>
<% end %>
<div class="panel left">
    <h1>Buddies' Chats</h1>
    <% @chats.each do |chat| %>
        <div class="ribbitWrapper">
            <a href="<%= user_path chat.user %>">
            <img class="avatar" src="<%= chat.user.url %>">
            <span class="name"><%= chat.user.name %></span>
            </a>
            @<%= chat.user.username %>
            <span class="time"><%= time_ago_in_words(chat.created_at) %></span>
            <p> <%= chat.content %> </p>
        </div>
    <% end %>
</div>

app/views/users/index.html.erb
<div id="ribbits" class="panel left">
    <h1>Public Profile</h1>
    <% @users.each do |user| %>
    <div class="ribbitWrapper">
        <a href="<%= user_path user %>">
        <img class="avatar" src="<%= user.url %>">
        <span class="name"><%= user.name %></span>
        </a>
        @<%= user.username %>
        <p>
        <%= user.chats.size %> Chats
        <span class="spacing"><%= user.followers.count %> Followers</span>
        <span class="spacing"><%= user.followeds.count %> Following</span>
        </p>
        <% if user.chats.first %>
        <p><%= user.chats.first.content %></p>
        <% end %>
    </div>
    <% end %>
</div>

app/views/users/new.html.erb
<div id="img">
  <%= image_tag("gfx/chat1.png") %>
</div>
<div class="panel right">
  <h1>New to Chatter?</h1>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <%= f.text_field :username, placeholder: "username" %>
    <%= f.text_field :name, placeholder: "name" %>
    <%= f.text_field :email, placeholder: "email" %>
    <%= f.password_field :password, placeholder: "password" %>
    <%= f.password_field :password_confirmation, placeholder: "password" %>
    <%= f.submit "Create Account" %>
  <% end %>
</div>

app/views/users/show.html.erb
<% if current_user %>
<div id="createRibbit" class="panel right">
    <h1>Create a Chatter</h1>
    <p>
    <%= form_for @chat do |f| %>
        <%= f.text_area :content, class: 'ribbitText' %>
        <%= f.submit "chat!" %>
    <% end %>
    </p>
</div>
<% end %>
<div id="ribbits" class="panel left">
    <h1>Your Chatter Profile</h1>
    <div class="ribbitWrapper">
        <img class="avatar" src="<%= @user.url %>">
        <span class="name"><%= @user.name %></span> @<%= @user.username %>
        <p>
        <% if current_user and @user != current_user %>
            <% if current_user.following? @user %>
                <%= form_tag relationship_path, method: :delete do %>
                <%= submit_tag "Unfollow" %>
                <% end %>
            <% else %>
                <%= form_for @relationship do %>
                <%= hidden_field_tag :followed_id, @user.id %>
                <%= submit_tag "Follow" %>
                <% end %>
            <% end %>
        <% end %>
        <%= @user.chats.size %> chats
        <span class="spacing"><%= @user.followers.count %>Followers</span>
        <span class="spacing"><%= @user.followeds.count %> Following</span>
        </p>
    </div>
</div>
<div class="panel left">
    <h1>Your Chats</h1>
    <% @user.chats.each do |chat| %>
        <div class="ribbitWrapper">
            <img class="avatar" src="<%= @user.url %>">
            <span class="name"><%= @user.name %></span>
            @<%= @user.username %>
            <span class="time"><%= time_ago_in_words(chat.created_at) %></span>
            <p> <%= chat.content %> </p>
        </div>
    <% end %>
</div>